#!/bin/tcsh

limit coredumpsize 10000

if ( "$1x" == "x" ) then
	echo "Using default port 9000."
	echo "Using logfile /home/TOC/toc/log/toc9000."
	/home/TOC/toc/src/nicedb 9000 >>&! /home/TOC/toc/log/toc9000 &
	echo "Done. nicedb is now maintaining TOC at port 9000."
else 
	echo "Using port $1 instead of default port 9000."
	echo "Using logfile /home/TOC/toc/log/toc$1."
	/home/TOC/toc/src/nicedb $1 >>&! /home/TOC/toc/log/toc$1 &
	echo "Done. nicedb is now maintaining TOC at port $1."
endif


