#!/bin/bash -x
# By Killuminati

cd /mnt/e/ToC/src
rm *.o
rm merc
make
rm *.o
rm ../area/merc
cp merc ../area
rm merc
cd ..
sleep 1
pkill -e merc
pkill -e immortal
pkill -e startup
sleep 2
./startup &
